---
adminUser: admin
adminPassword: "admin"

# Ensure we don't use an existing secret
admin:
  existingSecret: ""

# only 2 replicasets with 0 replicas set for rollback purposes
revisionHistoryLimit: 2

service:
  type: NodePort
  port: 3000
  nodePort: 30070

nodeSelector:
  kubernetes.io/hostname: hl-worker-01

# Configure Prometheus and OpenTelemetry Collector as data sources
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local # Simple prometheus service name
        access: proxy
        isDefault: true

      - name: OpenTelemetry
        type: prometheus
        url: http://otelc-opentelemetry-collector.monitoring.svc.cluster.local:8889
        access: proxy

# Import some useful dashboards
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: false
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    argo-cd:
      url: https://raw.githubusercontent.com/MhouneyLH/homelab/master/src/k8s/apps/monitoring/grafana/dashboards/argo_cd_dashboard.json
    kubernetes-cluster:
      url: https://raw.githubusercontent.com/MhouneyLH/homelab/master/src/k8s/apps/monitoring/grafana/dashboards/k8s_cluster_dashboard.json
    mosquitto:
      url: https://raw.githubusercontent.com/MhouneyLH/homelab/master/src/k8s/apps/monitoring/grafana/dashboards/mosquitto_dashboard.json
    node-exporter:
      url: https://raw.githubusercontent.com/MhouneyLH/homelab/master/src/k8s/apps/monitoring/grafana/dashboards/node_exporter_dashboard.json
    prometheus:
      url: https://raw.githubusercontent.com/MhouneyLH/homelab/master/src/k8s/apps/monitoring/grafana/dashboards/prometheus_dashboard.json
    traefik:
      url: https://raw.githubusercontent.com/MhouneyLH/homelab/master/src/k8s/apps/monitoring/grafana/dashboards/traefik_dashboard.json
