---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Install before everything else
spec:
  project: default

  source:
    repoURL: https://github.com/MhouneyLH/homelab.git
    targetRevision: master
    path: src/k8s/infrastructure

  destination:
    server: https://kubernetes.default.svc
    namespace: default # Namespaces are cluster-scoped, but we need a target

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
