---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MhouneyLH/homelab.git
    targetRevision: master
    path: src/k8s/apps/services/mosquitto/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: services

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
