---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # After infrastructure, before apps
spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "82.13.1"
      helm:
        releaseName: prometheus
        # Force CRD installation
        parameters:
          - name: prometheusOperator.manageCrds
            value: "true"
          - name: crds.enabled
            value: "true"
        valueFiles:
          - $values/src/k8s/apps/monitoring/prometheus/values.yml

    - repoURL: https://github.com/MhouneyLH/homelab.git
      targetRevision: master
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true # Force replace resources
      - ServerSideApply=true # Use server-side apply for CRDs
