---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # Apply before most apps
spec:
  project: default

  source:
    repoURL: https://github.com/MhouneyLH/homelab.git
    targetRevision: master
    path: src/k8s/rbac

  destination:
    server: https://kubernetes.default.svc
    namespace: rbac

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
