---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gramps-backup
  namespace: services
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
