---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: services
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      nodeSelector:
        kubernetes.io/hostname: hl-worker-01
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.22
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: websocket
              containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: /mosquitto/data
        - name: mosquitto-exporter
          image: sapcc/mosquitto-exporter:v0.8.0
          args:
            - --endpoint
            - tcp://127.0.0.1:1883
            - --bind-address
            - 0.0.0.0:9234
          ports:
            - name: metrics
              containerPort: 9234
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 15
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
