---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBIL6OnK1+cQXG/7cqFJ1ccHtI0ujkrdTziFu3KT128TcoIRzHv2IoPPM/TNgE6FU3oYm8ag+dx69RxubFujj7tgL8a6TinJArmx0A4DQWNv4G2KI32oWiomuBSq5v7U7fSUwnHNaNbKn5aI5gOlSXvVVfv0HfWccwh6HNuOYG3KBlEIwLY3ahU9JM3PgtgAEWKMFUXpZm8woW1C4+Yd0SYFZwOYY9Q08tLiCRJJVeS8pbU4Pxs6zoMppbcedfIxVGcggsypDY27zoAx2ZDJvwN1DNjiuWjMEMDWMePoVFRfnWX9IT7be3QBZctGJwvOInYkQXBECd3bqQ7D6p8ZgunAiF+1VJDkx1MBeC6sFmeOJNdwgr/ThYyWfSpAW/aoOK40Wz+vBfIS0d9UGo5jTJTzOwlWS1C0IR/EO3yNaaF5E6l1lKT7jYkQKMIS+7vpLrwhLwpZzdZxq4e3JAyx6uWJKEbG0fSI75BM+Os00RxWVRpMlVWDJ72RfRYSCqX2TtVVT3Kj7XbaGg/0RlVRPr6SryL9xdziMvnCMKg8i+tWMaoMGF7m7eoqE3gE9SW7asqYMuZTNZ5gx4aYCNeD/OAt8YbhRlEhOaE3Ovr/X8aroY7yeI1uRjN6rn4H8oi720WPdOYOfxBbqPQkCyH09O8tuLxa/8bh1iTMlc8ddmBYI3htWIpdppzBlEDMy1KlNOAI/adJDJG2bIAVL7y5ngVE9XrW+k=
    admin-user: AgA62tQYiZZ34VYgfiuflZjdyQsdPXkKW7rwK+GF4+Pd605dkpcfbHuB+gPIP6oO2GjHfgHo3cr9Jo/L+l5WiHHBroSXTgCs85jif2jcTAsSmh54rTY+YWefmHksPo+94yUBnDLT7urNaHt7ytbngi6VrqNXj0+UJVLpjR3EligCafas/x9wtMYxoPHEMogOsrORQdpQ5b4SVuAS/eFVEbmA8dMv2Eb33Svhg22D93vFVeSNliDc/fR+wF/p7fu5Me79jjz3xpIiixQhGk6rX9UeaM71L4eE/tpdoESj2H+Brkluvjk+BjYWBvI4rHZVjADzK4AlGxd/L0BizXsNGQyNpYJVmmTsIMMOIXf/jmgqX5E8RMqHZcbqH0smtf91AMsJiWScaEgfZdpo2+/27ZgEgSeo/eLQyEb9lDMdD/ijolIO230rMJkZ2shtj6o3gUp0G1XP0Bi7usNSWH8MpK5Z+eEG0pRLVnL1Kytpz0lMZXCeRaoDneQcfzQPgD87hACxjFx5BLP1ZbzAtZqmB98QRVIi4fTq4z8wH6Lu2C+RQz7JljTJ7i5kq1CZri5CKHAzJpZWbFrIqeL9g5y08g3Hzbs3QbCkTP8IqJbk19Y6Tgu4U0jvzl2OkLCg7nwt97HFP7hFmS/le1bJdVUOWEyUmCFuVoCAuuLXTnHr19XL/cPX5+79Ya29fDCXZ5oxdbpsbCV5Jg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
