---
# Node selector - run on control plane
nodeSelector:
  node-role.kubernetes.io/control-plane: ""

tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

service:
  enabled: true
  single: true
  spec:
    type: NodePort

# entrypoints (listeners)
ports:
  web:
    port: 15000
    expose:
      default: true
    exposedPort: 15000
    protocol: TCP
    nodePort: 30015
  websecure:
    port: 15001
    expose:
      default: true
    exposedPort: 15001
    protocol: TCP
    nodePort: 31501

# dashboard
api:
  dashboard: true
  insecure: true

# k8s traefik provider as ingress controller
providers:
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true
      namespace: traefik

logs:
  general:
    level: INFO

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
