---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-password
  namespace: platform
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCTp0jDpXzyrfGnj9wtM6fIi3ADNlyg0RFtt+28qWkMvNErBQ0a1iQaB8Q6LaqJbzl4ucsKaKDLUFUiHb4MqyaSFjmAOXZou30kH/PWHQpNw4NgorpKOYSwwPFwEbWnN3/gRHPKdNQxsxTy/n96FxWEgfgXpnIPU5KsB+wMeHxSSIx1Y4fjYr2lovkDK5el3RlkGglM41wsN9ogwpNZBhqSZK4Jwv8Wlc0WnQ9KiOEBdAqfNFOc4tsJNIr3Q0c/+cTyxJKGfwfu1Baf3ui81Te8gH+CNqCn/waxssOod/r4/63jOOuGHJDWmSyoMkYZtGPp+eTQuga5bgjMsdTX4aP6b0ecQYyHa3isR+eNimmK0ecIU2DmO/jx5FVRfdvl2aqcpIhTBjl2xOqujvqDgHU3rGTwJl4WB6p46Dp3eSwRBGeLNqulSOwrK2RzB4DCPPOfaLO9mnTOLDdBCU1GMYXP1jkjlDfN65Nte51ZYq7dj3SYvEejMVqiayAv8p6ebUKnxz6/+iHMISEiHxlZoXVzowFuXcpEv5SCsM60cuHRCxmQ0uQkhsTwbMc9o4ANmrsTWEp+U8IJIKWU2vC5WQT78ARYQIXbzXuhiAGCRlta12Z4TB9W3npnHS3z2kjWj+d98K+gwIQy/5auX6bflcWM6qjv/9p0xe60NKrPxNhEjkgfmzB8mQtTgwvc7DyFHQwyCx1hjFCbnJPqa2l5aqw+9YrDhTosViQ=
  template:
    metadata:
      name: harbor-admin-password
      namespace: platform
    type: Opaque
