---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-secret-key
  namespace: platform
spec:
  encryptedData:
    secretKey: AgBq9vX3GwpB8E6beNBKhnNaHsH93C/pzKNUtHeA0XmiiwT305dzAM4S60mRr4sWRBSwi1S/YMFjY8tqZ2/5RlPDCgD1qsklMdr/ho/D//tKf60zrydHTiSedjqjPBl4Tftr9sRd1j/4FtOQ1qUfdsnnpk+2p/6CEQjKkEXmSm3FwRWaYLLcoGAvLv4gaGzCAkchqlf6w1MtneyUAcf7PqpNgLVVcmUuQUkNCq9P+sVCBzVCMjJbfn/IWTkCZbu8ZqnrnBsJQLtBRgWm5iQ3E/YOzF2Z1/89RDI8Uqdsw3ndDf4V+wBygrwkVgTNT9USMglSSSMPKrLHvHIBzfmEKo58gRkLrc1/9gnjaO/s9HBdngywDz4pKxQGaOHjOjEXNzGdcLFEmic/wgHC7xhRdXvS9uIpdRa6ZIqALG8StgwdC5nCgZuDQmhpgjXsxlsx0NolVXgFlix0nKWapwP83b3P1Gr8IMEhiDjF6DB51OOflayJ0zRyErT2O+ts+fN0rA0IdwomM+sLy14HIFu+i94vapbP/1MgGk6DD7KA1X5Qg6DIj8t4eTxaxOEUZbLziLsoB1UDeqta7LRYkvQVcyz10Aj2Hl8iNIBvAnbztdMgu77vd7mTCvt5kEzK45s59Cd7FYGlumaMLbrzQjyjwrsWPRAmOmCKAya6sPJoYVDG7OXW0xkPAmYmZiMwiaRb7F0tnE9d2fL7HiqznGFHwCQj
  template:
    metadata:
      name: harbor-secret-key
      namespace: platform
    type: Opaque
