{
 "title": "Prometheus",
 "description": "Prometheus stats and troubleshooting",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "2m" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime of the Prometheus application",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Prometheus build version",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "prometheus_build_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Mem Usage %",
   "type": "stat",
   "description": "% Mem max usage (max RSS/Limit), should not exceed 70%, otherwise Prometheus may crash",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes{job=\"prometheus\"})/avg(kube_pod_container_resource_limits_memory_bytes{container=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "SA %",
   "type": "stat",
   "description": "Service Availability over past 2 weeks (up and running because targets could be scraped)",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{job=\"prometheus\"}[2w]))"
    }
   ]
  },
  {
   "title": "DA %",
   "type": "stat",
   "description": "Data Availability : Current % of targets which are available for all Prometheus jobs, ideally it should be 100% meaning that all nodes, all containers are properly scraped, ie Prometheus DA =100%",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)/count(up)" }
   ]
  },
  {
   "title": "Scraped",
   "type": "stat",
   "description": "The number of open head chunks.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(scrape_samples_scraped)" }
   ]
  },
  {
   "title": "Ingested/Hour",
   "type": "stat",
   "description": "Sample ingestion rate good to know for dimensioning the CPU and memory of Prometheus",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[1h])"
    }
   ]
  },
  {
   "title": "WAL Corruptions",
   "type": "stat",
   "description": "total WAL corruptions tsdb",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_wal_corruptions_total{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "description": "% CPU max usage (max usage/Limit), should not exceed 70%, otherwise Prometheus may be unresponsive",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(irate(process_cpu_seconds_total{job=\"prometheus\"}[1m]))/avg(kube_pod_container_resource_limits_cpu_cores{container=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Storage Usage %",
   "type": "stat",
   "description": "storage usage available",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (persistentvolumeclaim)(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"platform-monitoring-prometheus-volume-claim\"}*100/kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"platform-monitoring-prometheus-volume-claim\"})"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "stat",
   "description": "storage size available ",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"platform-monitoring-prometheus-volume-claim\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "max_over_time(go_memstats_alloc_bytes{job=\"prometheus\"}[$interval])",
     "legendFormat": "Max Go"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}",
     "legendFormat": "Allocated bytes"
    },
    {
     "expr": "min_over_time(go_memstats_alloc_bytes{job=\"prometheus\"}[$interval])",
     "legendFormat": "Min Go"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_memory_bytes{container=\"prometheus\"})",
     "legendFormat": "Req"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_memory_bytes{container=\"prometheus\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"prometheus\"}[1m])",
     "legendFormat": "1m rate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[5m])",
     "legendFormat": "5m rate"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests_cpu_cores{container=\"prometheus\"})",
     "legendFormat": "Req"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits_cpu_cores{container=\"prometheus\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Top Scraped Jobs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(3,scrape_samples_scraped)",
     "legendFormat": "{{job}} | {{pod}} | {{instance}}"
    }
   ]
  },
  {
   "title": "Scraped samples by job",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job) (scrape_samples_scraped)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Scrape Duration Interval",
   "type": "timeseries",
   "description": "Scrape Duration will show how long the scrapes are taking, with percentiles available as series.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "prometheus_target_interval_length_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{quantile}} ({{interval}})"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " max(scrape_duration_seconds) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Down Targets",
   "type": "table",
   "description": "Any targets that is not scraped",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "up == 0" },
    {
     "expr": "(sum by (job)(up)/count by (job)(up))<.99",
     "legendFormat": "Coverage"
    }
   ]
  },
  {
   "title": "Data Availability",
   "type": "timeseries",
   "description": "% of targets which are available for all Prometheus jobs, ideally it should be 100% meaning that all nodes, all containers are properly scraped, ie Prometheus DA =100% You can look at the table on the right side to check what targets were not scraped.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "sum(up)/count(up)", "legendFormat": "Coverage" }
   ]
  },
  {
   "title": "Scrape Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scraped samples by job/instance/pod",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (job,instance,pod) (scrape_samples_scraped)",
       "legendFormat": "{{job}} {{instance}} {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}