{
 "title": "Tempo & OtelC Overview",
 "description": "OpenTelemetry & Tempo Performance Monitoring",
 "tags": [
  "Traces",
  "OpenTelemetry",
  "Tempo"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "tempo_namespace",
    "label": "TempoNamespace",
    "query": {
     "query": "label_values(tempo_ingester_bytes_received_total,namespace)"
    }
   },
   {
    "name": "otel_service",
    "label": "OTEL_Service",
    "query": {
     "query": "label_values(otelcol_receiver_accepted_spans,service)"
    }
   },
   {
    "name": "tempo_distributor_service",
    "label": "TempoDistributorService",
    "query": {
     "query": "label_values(tempo_discarded_spans_total{namespace=\"$tempo_namespace\"},service)"
    }
   },
   {
    "name": "tempo_ingester_service",
    "label": "TempoIngesterService",
    "query": {
     "query": "label_values(tempo_ingester_traces_created_total{namespace=\"$tempo_namespace\"},service)"
    }
   },
   {
    "name": "tempo_querier_service",
    "label": "TempoQuerierService",
    "query": {
     "query": "label_values(tempo_querier_worker_request_executed_total{namespace=\"$tempo_namespace\"},service)"
    }
   },
   {
    "name": "tempo_compactor_service",
    "label": "TempoCompactorService",
    "query": {
     "query": "label_values(tempodb_compaction_blocks_total{namespace=\"$tempo_namespace\"},service)"
    }
   },
   {
    "name": "tempo_metrics_generator",
    "label": "TempoMetricsGenService",
    "query": {
     "query": "label_values(tempo_metrics_generator_active_processors{namespace=\"$tempo_namespace\"},service)"
    }
   },
   {
    "name": "tempo_memcached_service",
    "label": "TempoMemcachedService",
    "query": {
     "query": "label_values(memcached_current_connections{namespace=\"$tempo_namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tempo metrics-generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "active processor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tempo_metrics_generator_active_processors) by (processor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pushes & dropped spans in the distributor queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_queue_pushes_total{service=\"$tempo_distributor_service\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "{{tenant}} push"
    },
    {
     "expr": "sum(rate(tempo_distributor_queue_pushes_failures_total{service=\"$tempo_distributor_service\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "{{tenant}} push failure"
    }
   ]
  },
  {
   "title": "Distributor pushes to the generator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_metrics_generator_pushes_total{service=\"$tempo_distributor_service\"}[$__rate_interval])) by (metrics_generator)",
     "legendFormat": "pushes {{metrics_generator}}"
    },
    {
     "expr": "sum(rate(tempo_distributor_metrics_generator_pushes_failures_total{service=\"$tempo_distributor_service\"}[$__rate_interval])) by (metrics_generator)",
     "legendFormat": "push failures {{metrics_generator}}"
    }
   ]
  },
  {
   "title": "Discarded spans reason in the generator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(tempo_metrics_generator_spans_discarded_total{}[$__interval])) by (reason, tenant)",
     "legendFormat": "{{tenant}} {{reason}}"
    }
   ]
  },
  {
   "title": "Remote write failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_remote_storage_samples_failed_total{service=\"$tempo_metrics_generator\"}[$__rate_interval])) by (remote_name, tenant)",
     "legendFormat": "{{tenant}} sample failed {{remote_name}}"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_samples_dropped_total{service=\"$tempo_metrics_generator\"}[$__rate_interval])) by (remote_name, tenant, reason)",
     "legendFormat": "{{tenant}} sample dropped {{remote_name}}: {{reason}}"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_exemplars_failed_total{service=\"$tempo_metrics_generator\"}[$__rate_interval])) by (remote_name, tenant)",
     "legendFormat": "{{tenant}} exemplar failed {{remote_name}}"
    },
    {
     "expr": "sum(rate(prometheus_remote_storage_exemplars_dropped_total{service=\"$tempo_metrics_generator\"}[$__rate_interval])) by (remote_name, tenant, reason)",
     "legendFormat": "{{tenant}} exemplar dropped {{remote_name}}: {{reason}}"
    }
   ]
  },
  {
   "title": "Max active series limited",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(tempo_metrics_generator_registry_series_limited_total{service=\"$tempo_metrics_generator\"}[$__rate_interval])) by (tenant)",
     "legendFormat": "{{tenant}} limited"
    }
   ]
  },
  {
   "title": "Remote write failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "traces_service_graph_request_failed_total",
     "legendFormat": "{{tenant}} sample failed {{remote_name}}"
    }
   ]
  },
  {
   "title": "SpanMetrics span call rate by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_calls_total[$__rate_interval])) by(service,tenant)",
     "legendFormat": "{{tenant}} . {{service}}"
    }
   ]
  },
  {
   "title": "ServiceGraph client request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(rate(traces_service_graph_request_total[$__rate_interval])) by (tenant, client)",
     "legendFormat": "{{tenant}} . {{client}}"
    }
   ]
  },
  { "title": "Tempo Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Ingester created blocks ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_blocks_cleared_total{service=\"$tempo_ingester_service\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingester flushed blocks ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_blocks_flushed_total{service=\"$tempo_ingester_service\"}[$__rate_interval])) by (pod)",
     "legendFormat": "flushed: {{pod}}"
    },
    {
     "expr": "sum(rate(tempo_ingester_failed_flushes_total{service=\"$tempo_ingester_service\"}[$__rate_interval])) by (pod)",
     "legendFormat": "failed_flush: {{pod}}"
    }
   ]
  },
  {
   "title": "Blocks compaction & written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_blocks_total{service=\"$tempo_compactor_service\"}[$__rate_interval])) by (level)",
     "legendFormat": "compact_rate: level_{{level}}"
    },
    {
     "expr": "sum(rate(tempodb_compaction_bytes_written_total{service=\"$tempo_compactor_service\"}[$__rate_interval])) by (level)",
     "legendFormat": "written_bytes: level_{{level}}"
    }
   ]
  },
  {
   "title": "Objects combined & written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(tempodb_compaction_objects_combined_total{service=\"$tempo_compactor_service\"}[$__rate_interval])) by (level)",
     "legendFormat": "combined_rate: level_{{level}}"
    },
    {
     "expr": "sum(rate(tempodb_compaction_objects_written_total{service=\"$tempo_compactor_service\"}[$__rate_interval])) by (level)",
     "legendFormat": "written_rate: level_{{level}}"
    }
   ]
  },
  {
   "title": "blocklist length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(tempodb_blocklist_length) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ring state members",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(tempo_ring_members) by (service, state)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tempo cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Memcached free connection %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memcached_current_connections{service=\"$tempo_memcached_service\"} / memcached_max_connections{service=\"$tempo_memcached_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memcached memory used %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memcached_current_bytes{service=\"$tempo_memcached_service\"} / memcached_limit_bytes{service=\"$tempo_memcached_service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memcached current items",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memcached_current_items{service=\"$tempo_memcached_service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memcached command rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(memcached_commands_total{service=\"$tempo_memcached_service\"}[$__range])) by (command) > 0",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memcached read/write bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_read_bytes_total{service=~\"$tempo_memcached_service\"}[$__rate_interval])) by (service)",
     "legendFormat": "read: {{service}}"
    },
    {
     "expr": "sum(rate(memcached_written_bytes_total{service=~\"$tempo_memcached_service\"}[$__rate_interval])) by (service)",
     "legendFormat": "write: {{service}}"
    }
   ]
  },
  {
   "title": "memcache write duration percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tempo_memcache_request_duration_seconds_bucket{method=\"Memcache.Put\"}[$__rate_interval])) by (status_code, service, le))",
     "legendFormat": "Put p99: {{service}}/{{status_code}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tempo_memcache_request_duration_seconds_bucket{method=\"Memcache.Put\"}[$__rate_interval])) by (status_code, service, le))",
     "legendFormat": "Put p90: {{service}}/{{status_code}}"
    }
   ]
  },
  {
   "title": "memcache read duration percantage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tempo_memcache_request_duration_seconds_bucket{method=\"Memcache.GetMulti\"}[$__rate_interval])) by (status_code, service, le))",
     "legendFormat": "Get p99: {{service}}/{{status_code}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tempo_memcache_request_duration_seconds_bucket{method=\"Memcache.GetMulti\"}[$__rate_interval])) by (status_code, service, le))",
     "legendFormat": "Get p90: {{service}}/{{status_code}}"
    }
   ]
  },
  {
   "title": "memcache read/write avg duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(tempo_memcache_request_duration_seconds_sum[$__range])) by (method, service) / sum(increase(tempo_memcache_request_duration_seconds_count[$__range])) by (method, service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memcache avg duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(tempo_memcache_request_duration_seconds_sum{method=\"Memcache.GetMulti\"}) by (status_code, service) / sum(tempo_memcache_request_duration_seconds_count{method=\"Memcache.GetMulti\"}) by (status_code, service)",
     "legendFormat": "Get: {{service}}/{{status_code}}"
    },
    {
     "expr": "sum(tempo_memcache_request_duration_seconds_sum{method=\"Memcache.Put\"}) by (status_code, service) / sum(tempo_memcache_request_duration_seconds_count{method=\"Memcache.Put\"}) by (status_code, service)",
     "legendFormat": "Put: {{service}}/{{status_code}}"
    }
   ]
  },
  { "title": "Tempo Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Distributor discarded span",
   "type": "timeseries",
   "description": "Near by 0 is better.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum(rate(tempo_discarded_spans_total{service=\"$tempo_distributor_service\"}[$__rate_interval])) by (reason, tenant)",
     "legendFormat": "tenant: {{tenant}} reason:{{reason}}"
    }
   ]
  },
  {
   "title": "Distributor received spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_spans_received_total{service=\"$tempo_distributor_service\"}[$__rate_interval])) by (tenant, service)",
     "legendFormat": "{{tenant}}: {{service}}"
    }
   ]
  },
  {
   "title": "Ingester trace created",
   "type": "timeseries",
   "description": "Tempo Ingester trace created rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_ingester_traces_created_total{service=\"$tempo_ingester_service\"}[$__rate_interval])) by (pod, tenant)",
     "legendFormat": "{{tenant}}: {{pod}}"
    }
   ]
  },
  {
   "title": "Distributor recived bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_bytes_received_total{service=\"$tempo_distributor_service\"}[$__rate_interval])) by (tenant, service)",
     "legendFormat": "{{tenant}}: {{service}}"
    }
   ]
  },
  {
   "title": "Warning reason",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(tempo_warnings_total{}[$__interval])) by (tenant, reason, service)",
     "legendFormat": "{{tenant}}: {{reason}} service: {{service}}"
    }
   ]
  },
  { "title": "Tempo Querier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Querier rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum(rate(tempo_querier_worker_request_executed_total{service=\"$tempo_querier_service\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Querier ingester live traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "sum(tempo_ingester_live_traces{service=\"$tempo_ingester_service\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "OTEL Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "receiver accepted spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{service=\"$otel_service\"}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "receiver: {{receiver}} transport: {{transport}}"
    }
   ]
  },
  {
   "title": "🚨 receiver refused spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{service=\"$otel_service\"}[$__rate_interval])) by (receiver,transport)",
     "legendFormat": "receiver: {{receiver}} transport: {{transport}}"
    }
   ]
  },
  {
   "title": "Processor memory rss used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(otelcol_process_runtime_total_sys_memory_bytes{service=\"$otel_service\"}) by (pod)",
     "legendFormat": "runtime-{{pod}}"
    },
    {
     "expr": "sum(otelcol_process_memory_rss{service=\"$otel_service\"}) by (pod)",
     "legendFormat": "memory-rss-{{pod}}"
    }
   ]
  },
  {
   "title": "Processor memory_limiter refused spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_refused_spans{service=\"$otel_service\"}[$__rate_interval])) by (processor)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "processor batch send size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_batch_batch_send_size_bucket{service=\"$otel_service\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exporter send failed spans",
   "type": "timeseries",
   "description": "Check the backend service, <br>e.g: <br>    max_recv_msg_size_mib: 10943040<br>    read_buffer_size: 10943040 ...",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{service=\"$otel_service\"}[$__rate_interval])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exporter sent spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{service=\"$otel_service\"}[$__rate_interval])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exporter Queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "targets": [
    {
     "expr": "sum(otelcol_exporter_queue_size{service=\"$otel_service\"}) by (service)",
     "legendFormat": "queue_size: {{service}}"
    },
    {
     "expr": "sum(otelcol_exporter_queue_capacity{service=\"$otel_service\"}) by (service)",
     "legendFormat": "queue_capacity: {{service}}"
    }
   ]
  },
  {
   "title": "OTEL Collector tail-sampling processor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 }
  },
  {
   "title": "TailSampling processor received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_tail_sampling_new_trace_id_received{service=\"$otel_service\"}[$__rate_interval])) by (service_name)",
     "legendFormat": "new received"
    },
    {
     "expr": "sum(rate(otelcol_processor_tail_sampling_count_traces_sampled{service=\"$otel_service\"}[$__rate_interval])) by (service_name)",
     "legendFormat": "sampled"
    },
    {
     "expr": "sum(rate(otelcol_processor_tail_sampling_sampling_trace_removal_age_sum{service=\"$otel_service\"}[$__rate_interval])) by (service_name) / sum(rate(otelcol_processor_tail_sampling_sampling_trace_removal_age_count{service=\"$otel_service\"}[$__rate_interval])) by (service_name)",
     "legendFormat": "removal time"
    }
   ]
  },
  {
   "title": "TailSampling processor drapped too early",
   "type": "timeseries",
   "description": "Near by 0 is better.<br>\nshould more num_traces or decision_wait time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_tail_sampling_sampling_trace_dropped_too_early{service=\"$otel_service\"}[$__rate_interval])) by (service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "trace removal from memory time",
   "type": "heatmap",
   "description": "Time (in seconds) from arrival of a new trace until its removal from memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_tail_sampling_sampling_trace_removal_age_bucket{service=\"$otel_service\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sampling traces on memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "targets": [
    {
     "expr": "sum(otelcol_processor_tail_sampling_sampling_traces_on_memory{service=\"$otel_service\"}) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dicision Latency Time",
   "type": "timeseries",
   "description": "Dicision Latency Time percentage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(otelcol_processor_tail_sampling_sampling_decision_latency_bucket{service=\"$otel_service\"}[$__rate_interval])) by (le))",
     "legendFormat": "decision latency p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(otelcol_processor_tail_sampling_sampling_decision_latency_bucket{service=\"$otel_service\"}[$__rate_interval])) by (le))",
     "legendFormat": "decision latency p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(otelcol_processor_tail_sampling_sampling_decision_latency_bucket{service=\"$otel_service\"}[$__rate_interval])) by (le))",
     "legendFormat": "decision latency p50"
    }
   ]
  },
  {
   "title": "TailSampling policy sampled trace count / hours",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_tail_sampling_count_traces_sampled{service=\"$otel_service\", sampled=\"true\"}[$__rate_interval])) by (policy, sampled)",
     "legendFormat": "{{policy}}: sampled"
    },
    {
     "expr": "sum(rate(otelcol_processor_tail_sampling_count_traces_sampled{service=\"$otel_service\", sampled=\"false\"}[$__rate_interval])) by (policy, sampled)",
     "legendFormat": "{{policy}}: ignore"
    }
   ]
  },
  { "title": "OTEL exporter loadbalancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 175 } },
  {
   "title": "backends in use",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(otelcol_loadbalancer_num_backends{service=\"$otel_service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "backend update count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(otelcol_loadbalancer_num_backend_updates{service=\"$otel_service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loadbalancer backend success count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 176 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_loadbalancer_backend_outcome{service=\"$otel_service\"}[$__rate_interval])) by (exported_endpoint, success)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loadbalancer backend latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 176 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(otelcol_loadbalancer_backend_latency_bucket{service=\"$otel_service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95 latency"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(otelcol_loadbalancer_backend_latency_bucket{service=\"$otel_service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90 latency"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(otelcol_loadbalancer_backend_latency_bucket{service=\"$otel_service\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 latency"
    }
   ]
  }
 ]
}