---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-pull-secret
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgBRaN869Y2DrN4ORxPl9TClpUaF1Vde/8lLbK5YXqM+fEQ/qtVjGl/TWQLEDSJsB0HF0MjP1UsUqL2aBSRVo9MYz1PNX1XencuBIMfbdEzvIDciFAF8sNeAAv8FGmNdkkVCM7jKXkIsFw9HsmqNrfr4N73kmpmXW+8Ip6Ei8GtwQ9tX2ZwVJzNtbBWidpycELm3qc6qc3GmsDcwBXjqpTumki9ccJa7e5oRt5mdg1DKje2Qo3EkrQWnLBb02ARmLyyXl4x57IetGEH9YKeCTTOFDiRMKMTulWU2tcpeDp/bjq8aJ9UD7qu1L71zCYwVzFc7j4hDT3jkgoBOYfuppY4okiwdqPJTko+A9wrkoXI+L1FRg8sIjuCncUKtMj/AZjn1UXJlZkPEQG0zdLo9zQAqTdl8VerQLhQkuvbwd7Yd+dPyccD7j34PcKwnWtRbU6i8kAlX4Q3E7rRKufnwReNdnivymJvUcD8aoQXRzuRdRH4GnRy9NXn5Mzwa7akIIgdW2sssPLvU+2w1a0hpVXkpwYCtBF06bs6sthyGmSNEo84D6+OQMEznJF76TL0ZT20GCD3cyB4ShJj2se1J9Rx3DYnmr9b2ZOI+50M3V7gfvUi1heO8bWhAwPsDvlcz0ZdQjuSjyKPx+DU+i8V48q0bFNZXYvMoYLH6dpICmxLeBOtzMNuDy8npka0k/nIgGQ18tOfXzbyfH6YCXbm9A2vcqFKpoc7ZSJQBX9flG0d7Sl65G723IiOqkCc4SdTvThf7OjRvQItnkuDouYGE9q2WnoITrqEVuExrUNRbAuW309INpo9xPYh3ZB/Bts9ICoSgLbkUxCk20Afv6Bb9J2xI4/e6GpLt/91VSwSh+3Q4NZWM0l+cSSnGYU/j/6CjLm4nGb6gmEH/kGG5xAptJIYxOBFNm81gsQyHLjwoYOzd1dTwxWX0RJ+vaaZXd/C6qzh5vX5yea4ZNZd1iRS84TfkeKGry634sxraNCUSEw==
  template:
    metadata:
      name: harbor-pull-secret
      namespace: services
    type: kubernetes.io/dockerconfigjson
